# Generated by Django 5.2.7 on 2025-12-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paqueteria',
            field=models.CharField(blank=True, choices=[('FEDEX', 'FedEx'), ('DHL', 'DHL')], max_length=10, null=True),
        ),
    ]
